# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# use, git commit -m <message> --no-verify, to skip pre-commit hooks
# use SKIP, to skip specific hooks, e.g. SKIP=flake8 git commit -m <message>

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    #-   id: trailing-whitespace
    #-   id: end-of-file-fixer
    -   id: check-yaml
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   # Ruff version.
#   rev: v0.1.11
#   hooks:
#     # Run the linter.
#     - id: ruff
#     # Run the formatter.
#     - id: ruff-format
