# This workflow will check for code style with ruff

name: Run tests

on:
  push:
    branches: [ master, main, exercises_soren ]
  pull_request:
    branches: [ master, main, exercises_soren ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        # caching dependencies to speed up workflow
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Check code style with ruff
      run: |
        ruff check /jacob_mnist .
        ruff format /jacob_mnist .