name: "Run tests"

on:
  push:
    branches: [ master, main, daniel ]
  pull_request:
    branches: [ master, main, daniel ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        python-versions: [3.11]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r jacob_mnist/requirements.txt
        pip install -r jacob_mnist/requirements_tests.txt
    - name: Test with pytest
      run: |
        pytest -v jacob_mnist/tests